name: container_server_example
publish_to: none # not intended for publication to pub.dev

environment:
  sdk: ^3.4.0

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.2
  shelf_static: ^1.1.0
  json_annotation: ^4.8.1
  uuid: ^4.5.0


dev_dependencies:
  json_serializable: ^6.7.0
  build_runner: ^2.4.5
  http: ^1.2.0
  lints: ^4.0.0
  test: ^1.25.0
  test_process: ^2.1.0
